[package]
name = "image_go_fast"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3.2.12", features = ["derive"] }
hex = "0.4.3"
image = "0.24.2"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
